select COUNT(*) from products_data
select COUNT(*) from orders
select COUNT(*) from customers

--List all customers along with their city and state.
select * from customers
select * from orders
select * from products_data

--Show all orders placed in a specific month/year, with the customer's name.
select ob.*,datepart(month,ob.order_date) as mo,
datepart(year,ob.order_date) as ye,c.customer_id from orders as ob
 join customers as c on OB.customer_id = C.customer_id  

 --Find all products that belong to a specific category.
select product_name,category 
from products_data
where category='home'

--What is the total revenue (QuotedPrice × QuantityOrdered) generated by each product?
select ob.product_id,sum(p.price * ob.quantity) as totalrevenue 
from orders as ob 
join products_data as p on ob.product_id = p.product_id
group by ob.product_id 

--Which product category generates the most total revenue?
select p.category,sum(p.price * ob.quantity) as total_revenue from orders as ob
join products_data as p on ob.product_id = p.product_id
group by p.category

--What is the total amount spent by each customer, ranked highest to lowest?
select ob.customer_id,sum(p.price * ob.quantity) as totalrevenue 
from orders as ob 
join products_data as p on ob.product_id = p.product_id
group by OB.customer_id
order by totalrevenue desc

--List the top 5 best-selling products by quantity ordered.
select Top 5 ob.product_id,p.product_name,sum(quantity) as total_order from orders as ob
join products_data as p on OB.product_id = p.product_id
group by OB.product_id,p.product_name
order by total_order desc

--For each category, what is the total revenue generated?
select p.category,sum(p.price*ob.quantity) as tota_revenue from orders as ob
join products_data as p on OB.product_id = p.product_id
group by p.category

--Find customers who have placed more than 3 orders.
select c.customer_id,COUNT(order_id) as total_no_order from customers as c 
join orders as ob on c.customer_id = ob.customer_id
group by c.customer_id 
having count(OB.order_id) > 3

--Which products have never been ordered? (LEFT JOIN + IS NULL, or NOT IN/NOT EXISTS)
select p.product_id,p.product_name from orders as ob
left join products_data as p on ob.product_id = p.product_id 
where ob.product_id is null 

--What is the average order value (per order), and which orders are above that average?
SELECT 
    ob.order_id,
    SUM(p.price * ob.quantity) AS order_total,
    CASE 
        WHEN SUM(p.price * ob.quantity) > (
            SELECT AVG(order_total)
            FROM (
                SELECT o.order_id, SUM(p2.price * o.quantity) AS order_total
                FROM orders AS o
                JOIN products_data AS p2 ON o.product_id = p2.product_id
                GROUP BY o.order_id
            ) AS sub
        ) THEN 'Above Average'
        ELSE 'Below Average'
    END AS comparison
FROM orders AS ob
JOIN products_data AS p ON ob.product_id = p.product_id
GROUP BY ob.order_id
ORDER BY order_total DESC;

---Rank customers by total spend using RANK() or DENSE_RANK()
select c.customer_id,
SUM(p.price * ob.quantity) as total_spend,
DENSE_RANK()over (order by sum(p.price * ob.quantity)desc) as ranks
from customers as c 
join orders as ob on c.customer_id = OB.customer_id
join products_data as p on OB.product_id = p.product_id
group by c.customer_id

--Find the month with the highest total order revenue
select DATEPART(MONTH,OB.order_date) as mo, 
sum(ob.quantity*p.price) as tota_revenue 
from orders as ob
join products_data as p on ob.product_id = p.product_id
group by DATEPART(MONTH,OB.order_date)
order by tota_revenue desc

--Compare each product's RetailPrice to the average RetailPrice within its category —
--is it above or below average? (correlated subquery, matches what you practiced before)
select p.product_id,p.product_name,p.category,p.price as retail_price,
     (select AVG(p2.price) from products_data as p2
     where p2.category = p.category) as avg_category_price,
  case 
      when p.price > (select AVG(p2.price)
                     from products_data as p2
                      where p2.category = p.category)
      then 'above average'
      else 'below average'
  end as comparison 
from products_data as p


